// <auto-generated />
namespace MobilePhoneAdministration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddContrCatandSIMCard : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddContrCatandSIMCard));
        
        string IMigrationMetadata.Id
        {
            get { return "201802201613038_Add ContrCat and SIMCard"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
